name: "Generate VEX with Kubescape"
description: "Generate VEX with Kubescape"
inputs:
  helm-chart-path:
    description: "Path to Helm chart to test"
    required: true
  namespace:
    description: "Namespace to deploy the Helm chart into"
    default: "tests"
    required: false
  ready-condition:
    description: "Condition to wait for before collecting VEX info"
    required: false
  test-command:
    description: "Command to run to test the deployment"
    required: false

runs:
  using: "composite"
  steps:
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1
    
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.15.0

    - name: "Setup Kubescape"
      run: $GITHUB_ACTION_PATH/setup.sh
      shell: bash
    
    - name: "Install Helm Chart"
      env: 
        HELM_CHART_PATH: ${{ inputs.helm-chart-path }}
        READY_CONDITION: ${{ inputs.ready-condition }}
        TESTS_NAMESPACE: ${{ inputs.namespace }}
      run: $GITHUB_ACTION_PATH/install.sh
      shell: bash

    - name: "Run tests"
      env:
        TEST_COMMAND: ${{ inputs.test-command }}
        TESTS_NAMESPACE: ${{ inputs.namespace }}
      run: $GITHUB_ACTION_PATH/test.sh
      shell: bash
    
    - name: "Generate VEX"
      run: $GITHUB_ACTION_PATH/generate.sh
      env:
        TESTS_NAMESPACE: ${{ inputs.namespace }}
      shell: bash
    
    - name: Upload VEX document
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: VEX documents
        path: out/*.json
